declare const styles: {
  readonly m_xs: string
  readonly m_s: string
  readonly m_m: string
  readonly m_l: string
  readonly m_xl: string
  readonly mx_xs: string
  readonly mx_s: string
  readonly mx_m: string
  readonly mx_l: string
  readonly mx_xl: string
  readonly my_xs: string
  readonly my_s: string
  readonly my_m: string
  readonly my_l: string
  readonly my_xl: string
  readonly ml_xs: string
  readonly ml_s: string
  readonly ml_m: string
  readonly ml_l: string
  readonly ml_xl: string
  readonly mr_xs: string
  readonly mr_s: string
  readonly mr_m: string
  readonly mr_l: string
  readonly mr_xl: string
  readonly mt_xs: string
  readonly mt_s: string
  readonly mt_m: string
  readonly mt_l: string
  readonly mt_xl: string
  readonly mb_xs: string
  readonly mb_s: string
  readonly mb_m: string
  readonly mb_l: string
  readonly mb_xl: string
}

export default styles
