declare const styles: {
  readonly p_xs: string
  readonly p_s: string
  readonly p_m: string
  readonly p_l: string
  readonly p_xl: string
  readonly px_xs: string
  readonly px_s: string
  readonly px_m: string
  readonly px_l: string
  readonly px_xl: string
  readonly py_xs: string
  readonly py_s: string
  readonly py_m: string
  readonly py_l: string
  readonly py_xl: string
  readonly pl_xs: string
  readonly pl_s: string
  readonly pl_m: string
  readonly pl_l: string
  readonly pl_xl: string
  readonly pr_xs: string
  readonly pr_s: string
  readonly pr_m: string
  readonly pr_l: string
  readonly pr_xl: string
  readonly pt_xs: string
  readonly pt_s: string
  readonly pt_m: string
  readonly pt_l: string
  readonly pt_xl: string
  readonly pb_xs: string
  readonly pb_s: string
  readonly pb_m: string
  readonly pb_l: string
  readonly pb_xl: string
}

export default styles
